# Generated by Django 4.2.7 on 2026-05-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='boost_count',
            field=models.IntegerField(default=1),
        ),
    ]
